### ISSUE TITLE
minor css issue

### ISSUE THREAD

**Issue by ghost** [littlebizzy/hovercraft#22]
minor styling issue as seen on:
![Screenshot 2023-02-03 205607](https://user-images.githubusercontent.com/108953087/216676634-7c9455c4-68be-4bfa-83bf-e67c4983a79b.png)
arrow position is all over the place.

**Comment by jessuppi** [comment]
Haha @yamanmucahit yes I noticed it start flying around the last few versions... it's incredibly difficult to style select menus seems. The example CSS was something I found here:

https://gist.github.com/TanvirAmi/630a95aab8256fef6fb6ddd5be0e6898

**Comment by ghost** [comment]
this works for me right now but only on desktop for some reason:
`.woocommerce-ordering:after {
    position: absolute;
	margin-left: -28px;
	margin-top: 2px;
    pointer-events: none;
    font-family: "Material Icons";
    font-size: 24px;
    content: ' \e5cf';
}`
and then i hide it on mobile.
gonna look into that link for sure tho.

**Comment by jessuppi** [comment]
Here is from Woo's default product attribute filter select menu widget:

```
<span class="selection"><span class="select2-selection select2-selection--single" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-gkew-container" role="combobox"><span class="select2-selection__rendered" id="select2-gkew-container" role="textbox" aria-readonly="true"><span class="select2-selection__placeholder">Example Attribute</span></span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span>
```

And the CSS rules:

```
.select2-container--default .select2-selection--single {
    background-color: #fff;
    border: 1px solid #aaa;
    border-radius: 4px;
}

.select2-container .select2-selection--single {
    box-sizing: border-box;
    cursor: pointer;
    display: block;
    height: 28px;
    user-select: none;
    -webkit-user-select: none;
}

.select2-container--default .select2-selection--single .select2-selection__arrow {
    height: 26px;
    position: absolute;
    top: 1px;
    right: 1px;
    width: 20px;
}

.select2-container--default .select2-selection--single .select2-selection__arrow b {
    border-color: #888 transparent transparent transparent;
    border-style: solid;
    border-width: 5px 4px 0 4px;
    height: 0;
    left: 50%;
    margin-left: -4px;
    margin-top: -2px;
    position: absolute;
    top: 50%;
    width: 0;
}
```

**Comment by jessuppi** [comment]
Honestly I'm not even sure how the downward arrow is rendered based on the code above but it's inside the `<b>` element on default WooCommerce sites.

**Comment by ghost** [comment]
#23 should do it.
