### ISSUE TITLE
Admin URLs should use `admin_url()`

### ISSUE THREAD

**Issue by siliconforks** [littlebizzy/hovercraft#29]
This issue is kind of similar to issue #28 in that it will only affect sites where WordPress is installed in a subdirectory (e.g., `https://example.com/example/`).

In [inc/media-sizes-verify.php](https://github.com/littlebizzy/hovercraft/blob/master/inc/media-sizes-verify.php) a URL is hard-coded: `<a href="/wp-admin/options-media.php">Review Settings</a>`. This link will be broken if WordPress is located in a subdirectory.

It should be `<a href="<?php echo esc_url( admin_url( 'options-media.php' ) ); ?>">Review Settings</a>`.

**Comment by jessuppi** [comment]
Done! Thanks @siliconforks 

Ref: https://github.com/littlebizzy/hovercraft/commit/b19a2c4b67dbde850bbec6baff841a9ced85140e
