### ISSUE TITLE
Mobile menu appears below WordPress admin bar

### ISSUE THREAD

**Issue by siliconforks** [littlebizzy/hovercraft#30]
When the user is logged in to WordPress, the mobile menu (`id="myNav"`, with z-index 9999) appears below the WordPress admin bar (`id="wpadminbar"`, with z-index 99999).

I would suggest increasing the z-index of the `myNav` element to something greater than 99999 so that it appears above the admin bar.

**Comment by jessuppi** [comment]
Thanks for your feedback @siliconforks 

Okay I haven't tested but pushed z-index to `999999` let's see if that helps for now ;)

Ref: https://github.com/littlebizzy/hovercraft/commit/26dd5eef7835fc3d444e2198e7159c327ca90fb9

**Comment by jessuppi** [comment]
On a related note, the search box overlay is currently `99999` which is the same as WP admin bar... I have seen that value used on a few other projects for their search overlays, not sure why.

Might need to tweak both of these again later.

**Comment by siliconforks** [comment]
The mobile menu seems to be fixed now - it's now appearing above the admin bar.

I tried the full screen search and the search overlay is indeed below the admin bar, although that doesn't really matter much as the admin bar is not covering anything important.

I did notice an issue with the full screen search close button, but that is unrelated - I'll create another issue for that.
