### ISSUE TITLE
Full screen search close button has `visibility: visible`

### ISSUE THREAD

**Issue by siliconforks** [littlebizzy/hovercraft#31]
When testing the full screen search, I noticed that it was difficult to click on the search icon - sometimes clicks would have no effect depending on where exactly the mouse was clicked.

Inspecting the HTML/CSS, I see that the full screen search close button is always being rendered on the page, even when the search overlay is not being displayed.  It can't actually be seen because it has zero opacity, but it has `visibility: visible` and is still able to receive mouse clicks and block clicks on elements underneath.

Ironically the thing it ends up covering is the search icon, but that is just a coincidence (also this will probably vary depending on your layout settings).

**Comment by jessuppi** [comment]
Thanks @siliconforks 

Yes the full screen search is causing major "click" conflicts, I wasn't sure why as I didn't dig into it yet. I'm going to try to change the default `visibility` as you suggest and see if that fixes it.

**Comment by jessuppi** [comment]
For now I removed the entire "reset" rules, this was part of the FOSS code that WP Beginner released:

```
/**
* Reset
* - Prevents Themes and other Plugins from applying their own styles to our full screen search
*/
#full-screen-search,
#full-screen-search button,
#full-screen-search button.close,
#full-screen-search form,
#full-screen-search form div,
#full-screen-search form div input,
#full-screen-search form div input.search {
    background:none;
    float:none;
    font-size:100%;
    height:auto;
    list-style:none;
    outline:none;
    position:static;
    text-decoration:none;
    text-indent:0;
    width:auto;
    visibility:visible;
    overflow:visible;
    margin:0;
    padding:0;
    line-height:1;
    transition: none;
}
```

Ref: https://wordpress.org/plugins/full-screen-search-overlay/

It seems to have fixed the issue for now. This is a theme-level search feature anyways, so we don't really need to worry so much about resetting CSS... however more optimization of the styling is still needed. Thanks!

Ref: https://github.com/littlebizzy/hovercraft/commit/09efbd7943aa42cb04da0bd938f4cdf291038255

**Comment by siliconforks** [comment]
It looks like that fixes the issue ... the only problem I see is that the close button has a background color now - you'll probably want to remove that.
